language: android

android:
  components:
    - platform-tools
    - tools
    - build-tools-27.0.3
    - android-27

before_install:
 - chmod +x ./gradlew
script:
  - ./gradlew clean build

deploy:
  provider: script
  script: ./gradlew bintrayUpload
  on:
    branch: master